#include "leaderboard.h"

#include <Wt/Dbo/Impl.h>

DBO_INSTANTIATE_TEMPLATES(DeviceToken)
DBO_INSTANTIATE_TEMPLATES(Device);
DBO_INSTANTIATE_TEMPLATES(Team);
DBO_INSTANTIATE_TEMPLATES(Player);
DBO_INSTANTIATE_TEMPLATES(Game);
DBO_INSTANTIATE_TEMPLATES(Ranking);
DBO_INSTANTIATE_TEMPLATES(Score);
DBO_INSTANTIATE_TEMPLATES(History);
